apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "popn.fullname" . }}-db
  labels:
    {{- include "popn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "popn.name" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "popn.name" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: db
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "popn.fullname" . }}-env
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "popn.fullname" . }}-env
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "popn.fullname" . }}-env
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ include "popn.fullname" . }}-db-pvc
