apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "popn.fullname" . }}-db-pvc
  labels:
    {{- include "popn.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
